# Section A: Data Structures & Control Structures

1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [4]:
nums = [1, 4, 6, 8, 10]
n = int(input("Enter a number to append: "))

#append
nums.append(n)
print("After append:", nums)

#extend
nums.extend([2, 3])
print("After extend:", nums)

# insert
nums.insert(1, 5) 
print("After insert:", nums)

#remove
nums.remove(1)  
print("After remove:", nums)

# pop
nums.pop(3) 
print("After pop:", nums)

# index
print("Index of 5:", nums.index(5))

# count
print("Count of 5:", nums.count(5))

# sort
nums.sort()
print("After sort:", nums)

# reverse
nums.reverse()
print("After reverse:", nums)

# clear
nums.clear()
print("After clear:", nums)

Enter a number to append: 9
After append: [1, 4, 6, 8, 10, 9]
After extend: [1, 4, 6, 8, 10, 9, 2, 3]
After insert: [1, 5, 4, 6, 8, 10, 9, 2, 3]
After remove: [5, 4, 6, 8, 10, 9, 2, 3]
After pop: [5, 4, 6, 10, 9, 2, 3]
Index of 5: 0
Count of 5: 1
After sort: [2, 3, 4, 5, 6, 9, 10]
After reverse: [10, 9, 6, 5, 4, 3, 2]
After clear: []


2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [8]:
s_names = ("Sam","Saba","Sidra")
print(s_names)
s_names[1] = "Sana" #tuples are immutable, after creating a tuple we can not change, add or remove.so, if we try to change it throws a typeerror

('Sam', 'Saba', 'Sidra')


TypeError: 'tuple' object does not support item assignment

3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [12]:
integers={1,4,3,4,2,5,5}
print(integers)
#sets are unordered collection of unique elements, it removes the duplicates automatically and keeps only copy of each value

{1, 2, 3, 4, 5}


4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [13]:
dict={"name":"Sana",
      "age" :21,
      "city":"Hyderabad"}
dict["age"]=22
dict["email"]="sana@gmail.com"
print(dict)

{'name': 'Sana', 'age': 22, 'city': 'Hyderabad', 'email': 'sana@gmail.com'}


5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [16]:
age = int(input("Enter your age: "))
if age>=18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

Enter your age: 65
You are eligible to vote.


6. Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [25]:
marks = int(input("Enter your marks: "))
if marks>=90:
            print("Grade: A")
elif marks >= 75:
            print("Grade: B")
elif marks >= 50:
            print("Grade: C")
else:
            print("Fail")
            

Enter your marks: 55
Grade: C


7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [29]:
n = int(input("Enter a number: "))
if n>0 and n%2==0:
    print("Number is positive and even")
elif n>0:
    print("Number is positive but not even")
elif n==0:
    print(n)
    print("Number is zero")
else:
    print(n)
    print("Number is negative")

Enter a number: -9
-9
Number is negative


# Section B: Numpy

8. Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [31]:
import numpy as np
scalar = np.array(5)
print("Scalar: ",scalar)
arr_1d = np.array([1,2,3,4,5])
print("One Dimensional Array: ",arr_1d)
arr_2d =np.arange(10,70,10).reshape(2,3)
print("Two Dimensional Array:\n ", arr_2d)


Scalar:  5
One Dimensional Array:  [1 2 3 4 5]
Two Dimensional Array:
  [[10 20 30]
 [40 50 60]]


9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [32]:
n= np.random.randint(0,101, size=(4,4))
print("Array:\n",n)


Array:
 [[ 8 15  6  4]
 [50 37 48  9]
 [14 48 65 95]
 [27 71 85  3]]


10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [35]:
import pandas as pd
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr)
df=pd.DataFrame(arr,columns=['A','B','C'])
print("Pandas DatAFrame:\n",df)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Pandas DatAFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# Section C: Exploring Pandas

11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [49]:
data = {
    'Name': ['sam','sana','anu','ritu','manu','harsh','gitu','ash','sana','ritu','sam'],  
    'Age':  [25, 22, 26, 35, 29, 31, 27, 30, 22, 35, 25],          
    'City': ['A','F','L','F','N','L','S','Y','F','F','A'],       
    'Salary': [50000, 55000, 52000, 58000, 60000, np.nan, 57000, 59000, np.nan, 58000, 50000]  
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
      Name  Age City   Salary
0     sam   25    A  50000.0
1    sana   22    F  55000.0
2     anu   26    L  52000.0
3    ritu   35    F  58000.0
4    manu   29    N  60000.0
5   harsh   31    L      NaN
6    gitu   27    S  57000.0
7     ash   30    Y  59000.0
8    sana   22    F      NaN
9    ritu   35    F  58000.0
10    sam   25    A  50000.0


In [50]:
print("DataFrame info:\n")
df.info()

print("DataFrame description:\n")
df.describe()


DataFrame info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    11 non-null     object 
 1   Age     11 non-null     int64  
 2   City    11 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 480.0+ bytes
DataFrame description:



Age        Salary
count  11.000000      9.000000
mean   27.909091  55444.444444
std     4.548726   3876.567783
min    22.000000  50000.000000
25%    25.000000  52000.000000
50%    27.000000  57000.000000
75%    30.500000  58000.000000
max    35.000000  60000.000000

In [51]:
print("Selected Columns (Name & City):\n")
print(df[['Name', 'City']])

Selected Columns (Name & City):

     Name City
0     sam    A
1    sana    F
2     anu    L
3    ritu    F
4    manu    N
5   harsh    L
6    gitu    S
7     ash    Y
8    sana    F
9    ritu    F
10    sam    A


In [52]:
df_without_city = df.drop('City', axis=1)
print("DataFrame without City column:\n", df_without_city)

DataFrame without City column:
      Name  Age   Salary
0     sam   25  50000.0
1    sana   22  55000.0
2     anu   26  52000.0
3    ritu   35  58000.0
4    manu   29  60000.0
5   harsh   31      NaN
6    gitu   27  57000.0
7     ash   30  59000.0
8    sana   22      NaN
9    ritu   35  58000.0
10    sam   25  50000.0


In [53]:
salary_mean = df['Salary'].mean()
df['Salary'].fillna(salary_mean, inplace=True)
print("DataFrame after filling missing Salary values:\n", df)


DataFrame after filling missing Salary values:
      Name  Age City        Salary
0     sam   25    A  50000.000000
1    sana   22    F  55000.000000
2     anu   26    L  52000.000000
3    ritu   35    F  58000.000000
4    manu   29    N  60000.000000
5   harsh   31    L  55444.444444
6    gitu   27    S  57000.000000
7     ash   30    Y  59000.000000
8    sana   22    F  55444.444444
9    ritu   35    F  58000.000000
10    sam   25    A  50000.000000


In [54]:
df.drop_duplicates(inplace=True)
print("DataFrame after removing duplicates:\n", df)

DataFrame after removing duplicates:
     Name  Age City        Salary
0    sam   25    A  50000.000000
1   sana   22    F  55000.000000
2    anu   26    L  52000.000000
3   ritu   35    F  58000.000000
4   manu   29    N  60000.000000
5  harsh   31    L  55444.444444
6   gitu   27    S  57000.000000
7    ash   30    Y  59000.000000
8   sana   22    F  55444.444444
